In [4]:
from definitions import *
import xlwt
r=moduli_space_sample(19000,[1,1,1,1])
len(r)

55680

In [6]:
r

[array([[0, 0],
        [1, 0],
        [4.9960036108132044e-15, 9.999999999999982e-08],
        [0.5, -0.8660253037844415],
        [0.999999999999995, 9.999999999999982e-08]], dtype=object),
 array([[0, 0],
        [1, 0],
        [4.9960036108132044e-15, 9.999999999999982e-08],
        [0.5, 0.8660255037844414],
        [0.999999999999995, 9.999999999999982e-08]], dtype=object),
 array([[0, 0],
        [1, 0],
        [4.9960036108132044e-15, -9.999999999999982e-08],
        [0.5, 0.8660253037844415],
        [0.999999999999995, -9.999999999999982e-08]], dtype=object),
 array([[0, 0],
        [1, 0],
        [4.9960036108132044e-15, -9.999999999999982e-08],
        [0.5, -0.8660255037844414],
        [0.999999999999995, -9.999999999999982e-08]], dtype=object),
 array([[0, 0],
        [1, 0],
        [4.9960036108132044e-15, 9.999999999999982e-08],
        [0.5, -0.8660253037844415],
        [0.999999999999995, 9.999999999999982e-08]], dtype=object),
 array([[0, 0],
        [1, 0],
 

In [5]:
from xlwt import Workbook
wb = Workbook()
sheet1 = wb.add_sheet('Sheet 1')

def clean(i):
    return (str(np.array(i[0]).tolist())+', '+str(np.array(i[1]).tolist())).replace('[','').replace(']','')

for count1, pent in enumerate(r):
    for count2, i in enumerate(pent):
        sheet1.write(count1, count2, clean(i))

wb.save('M5large.xls')