In [41]:
from definitions import *
import xlwt
r=moduli_space_sample(50,[0.6,0.6,0.6,1],math.pi/6)

('Angles and distances cannot form a valid pentagon.', 1.3353531789459703, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.276562668346533, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.3390683000374863, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.3626108109194521, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.433295140561019, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.3340361834712768, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.2850665300655884, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.2050462873247632, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.681770648197954, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.3727637564714315, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.3610888173713684, 1.2)
firstloop
('Angles and 

In [34]:
for c,i in enumerate(r[1]):
    print(i)
    print((str(np.array(i[0]).tolist())+', '+str(np.array(i[1]).tolist())).replace('[','').replace(']',''))

[0 0]
0, 0
[1 0]
1, 0
[array([1.59572637]) array([0.0714849])]
1.5957263708793665, 0.0714849007756141
[array([1.14627636]) array([-0.32600056])]
1.1462763645239693, -0.32600056032596264
[array([0.96896415]) array([0.2472013])]
0.9689641455754496, 0.2472013037773846


In [42]:
from xlwt import Workbook
wb = Workbook()
sheet1 = wb.add_sheet('Sheet 1')

def clean(i):
    return (str(np.array(i[0]).tolist())+', '+str(np.array(i[1]).tolist())).replace('[','').replace(']','')

for count1, pent in enumerate(r):
    for count2, i in enumerate(pent):
        sheet1.write(count1, count2, clean(i))

wb.save('genus 3.xls')

In [58]:
r

[array([[0, 0],
        [1, 0],
        [array([1.15586728]), array([0.57940089])],
        [array([1.06402145]), array([1.17232951])],
        [array([0.58499199]), array([0.81103907])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([1.15586728]), array([0.57940089])],
        [array([0.67683782]), array([0.21811046])],
        [array([0.58499199]), array([0.81103907])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([1.15586728]), array([-0.57940089])],
        [array([1.06402145]), array([-1.17232951])],
        [array([0.58499199]), array([-0.81103907])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([1.15586728]), array([-0.57940089])],
        [array([0.67683782]), array([-0.21811046])],
        [array([0.58499199]), array([-0.81103907])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([0.40189436]), array([0.04764081])],
        [array([0.37905971]), array([-0.55192451])],
        [array([0.94040649]), array([-0.3

In [50]:
rn=moduli_space_sample(50,[0.4,0.4,0.4,0.4],math.pi/2.5)

('Angles and distances cannot form a valid pentagon.', 0.9025303354360403, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8390797826006161, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8333429576286795, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8919772440328574, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8605073095911216, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.9291604471028839, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.9410295687907475, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8017345639055609, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8330280775089316, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8289985858170434, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8967695193679398, 0.8)
firstloop
('Angles a

In [59]:
rn

[array([[0, 0],
        [1, 0],
        [array([0.6]), array([3.8016247e-05])],
        [array([0.66846917]), array([0.39413442])],
        [array([0.28485666]), array([0.28081432])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([0.6]), array([3.8016247e-05])],
        [array([0.2163875]), array([-0.11328208])],
        [array([0.28485666]), array([0.28081432])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([0.6]), array([-3.8016247e-05])],
        [array([0.66846917]), array([-0.39413442])],
        [array([0.28485666]), array([-0.28081432])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([0.6]), array([-3.8016247e-05])],
        [array([0.2163875]), array([0.11328208])],
        [array([0.28485666]), array([-0.28081432])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([0.89890074]), array([0.38701284])],
        [array([0.52739612]), array([0.23874176])],
        [array([0.37754717]), array([-0.13212923])]], dtype=

In [61]:
wb0 = Workbook()
sheet2 = wb0.add_sheet('Sheet 1')


for count1, pent in enumerate(rn):
    for count2, i in enumerate(pent):
        sheet2.write(count1, count2, clean(i))

wb0.save('sphere.xls')

In [57]:
np.array_equal(rn,r)

False