In [62]:
from definitions import *
import xlwt
r=moduli_space_sample(350,[0.6,0.6,0.6,1],math.pi/6)

('Angles and distances cannot form a valid pentagon.', 1.2653507042042182, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.4658671888852872, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.3934985929763808, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.320114146273709, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.4332642170939718, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.3686212805326354, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.4686465472564558, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.5951760231197167, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.2231998999689229, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.7916725751147686, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.3150629404234682, 1.2)
firstloop
('Angles an

In [63]:
len(r)

2800

In [64]:
from xlwt import Workbook
wb = Workbook()
sheet1 = wb.add_sheet('Sheet 1')

def clean(i):
    return (str(np.array(i[0]).tolist())+', '+str(np.array(i[1]).tolist())).replace('[','').replace(']','')

for count1, pent in enumerate(r):
    for count2, i in enumerate(pent):
        sheet1.write(count1, count2, clean(i))

wb.save('genus 3.xls')

In [58]:
r

[array([[0, 0],
        [1, 0],
        [array([1.15586728]), array([0.57940089])],
        [array([1.06402145]), array([1.17232951])],
        [array([0.58499199]), array([0.81103907])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([1.15586728]), array([0.57940089])],
        [array([0.67683782]), array([0.21811046])],
        [array([0.58499199]), array([0.81103907])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([1.15586728]), array([-0.57940089])],
        [array([1.06402145]), array([-1.17232951])],
        [array([0.58499199]), array([-0.81103907])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([1.15586728]), array([-0.57940089])],
        [array([0.67683782]), array([-0.21811046])],
        [array([0.58499199]), array([-0.81103907])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([0.40189436]), array([0.04764081])],
        [array([0.37905971]), array([-0.55192451])],
        [array([0.94040649]), array([-0.3

In [65]:
rn=moduli_space_sample(350,[0.4,0.4,0.4,0.4],math.pi/2.5)

('Angles and distances cannot form a valid pentagon.', 0.8783836389992119, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8265055453248277, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8881000020776971, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8789420405385789, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.9526189704299572, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8984166753989494, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8970253815667849, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.9258796154001587, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8806379109544478, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8741171519596226, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8910981924165904, 0.8)
firstloop
('Angles a

In [66]:
len(rn)

2800

In [67]:
wb0 = Workbook()
sheet2 = wb0.add_sheet('Sheet 1')


for count1, pent in enumerate(rn):
    for count2, i in enumerate(pent):
        sheet2.write(count1, count2, clean(i))

wb0.save('sphere.xls')

In [57]:
np.array_equal(rn,r)

False