In [2]:
from definitions import *
import xlwt
r=moduli_space_sample(50,[0.6,0.6,0.6,1],math.pi/6)

('Angles and distances cannot form a valid pentagon.', 1.5844645250547935, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.4728627511930723, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.400142091182722, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.395977733686335, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.5976556502361623, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.3191930673930676, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.2740980444734475, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.5555113819331532, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.6455563112984457, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.3353043774143545, 1.2)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.2922600705874967, 1.2)
firstloop
('Angles and

In [34]:
for c,i in enumerate(r[1]):
    print(i)
    print((str(np.array(i[0]).tolist())+', '+str(np.array(i[1]).tolist())).replace('[','').replace(']',''))

[0 0]
0, 0
[1 0]
1, 0
[array([1.59572637]) array([0.0714849])]
1.5957263708793665, 0.0714849007756141
[array([1.14627636]) array([-0.32600056])]
1.1462763645239693, -0.32600056032596264
[array([0.96896415]) array([0.2472013])]
0.9689641455754496, 0.2472013037773846


In [36]:
from xlwt import Workbook
wb = Workbook()
sheet1 = wb.add_sheet('Sheet 1')

def clean(i):
    return (str(np.array(i[0]).tolist())+', '+str(np.array(i[1]).tolist())).replace('[','').replace(']','')

for count1, pent in enumerate(r):
    for count2, i in enumerate(pent):
        sheet1.write(count1, count2, clean(i))

wb.save('genus 3.xls')

In [37]:
rn=moduli_space_sample(50,[0.4,0.4,0.4,1],math.pi/6)

('Angles and distances cannot form a valid pentagon.', 1.4647369313764345, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.383426646701425, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.8405366802233912, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.1941068248025248, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.987629189271185, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.4870912034333847, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.6091955712750041, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.5807855425568087, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.6835764360063714, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 1.1340402789461874, 0.8)
firstloop
('Angles and distances cannot form a valid pentagon.', 0.9808911979220101, 0.8)
firstloop
('Angles and

In [38]:
rn

[array([[0, 0],
        [1, 0],
        [array([0.76901615]), array([0.32656769])],
        [array([1.05158951]), array([0.6096795])],
        [array([0.67322187]), array([0.73944054])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([0.76901615]), array([0.32656769])],
        [array([0.3906485]), array([0.45632874])],
        [array([0.67322187]), array([0.73944054])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([0.76901615]), array([-0.32656769])],
        [array([1.05158951]), array([-0.6096795])],
        [array([0.67322187]), array([-0.73944054])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([0.76901615]), array([-0.32656769])],
        [array([0.3906485]), array([-0.45632874])],
        [array([0.67322187]), array([-0.73944054])]], dtype=object),
 array([[0, 0],
        [1, 0],
        [array([0.6128925]), array([0.10073621])],
        [array([0.52554137]), array([-0.28960951])],
        [array([0.87161139]), array([-0.490197

In [ ]:
wb0 = Workbook()
sheet1 = wb.add_sheet('Sheet 1')


for count1, pent in enumerate(rn):
    for count2, i in enumerate(pent):
        sheet1.write(count1, count2, clean(i))

wb.save('sphere.xls')